// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basic_tasks.sql

package goqueries

import (
	"context"
	"database/sql"
	"time"
)

const addBasicTask = `-- name: AddBasicTask :one
INSERT INTO single_tasks (
  user_id,
  text,
  start,
  description,
  notification_params
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
RETURNING id, created_at, text, description, user_id, start, notification_params
`

type AddBasicTaskParams struct {
	UserID             int64          `db:"user_id"`
	Text               string         `db:"text"`
	Start              time.Time      `db:"start"`
	Description        sql.NullString `db:"description"`
	NotificationParams []byte         `db:"notification_params"`
}

func (q *Queries) AddBasicTask(ctx context.Context, db DBTX, arg AddBasicTaskParams) (SingleTask, error) {
	row := db.QueryRowContext(ctx, addBasicTask,
		arg.UserID,
		arg.Text,
		arg.Start,
		arg.Description,
		arg.NotificationParams,
	)
	var i SingleTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.NotificationParams,
	)
	return i, err
}

const countListBasicTasks = `-- name: CountListBasicTasks :one
SELECT COUNT(*)
FROM single_tasks as bt
LEFT JOIN smth2tags as s2t
  ON bt.id = s2t.smth_id
LEFT JOIN tags as t
  ON s2t.tag_id = t.id
WHERE bt.user_id = ?1
  AND (
    ?2 IS NULL 
    OR t.id IN (SELECT value FROM json_each(@tag_ids))
  )
`

type CountListBasicTasksParams struct {
	UserID int64       `db:"user_id"`
	TagIds interface{} `db:"tag_ids"`
}

func (q *Queries) CountListBasicTasks(ctx context.Context, db DBTX, arg CountListBasicTasksParams) (int64, error) {
	row := db.QueryRowContext(ctx, countListBasicTasks, arg.UserID, arg.TagIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBasicTask = `-- name: DeleteBasicTask :many
DELETE
FROM single_tasks
WHERE id = ?1
RETURNING id, created_at, text, description, user_id, start, notification_params
`

func (q *Queries) DeleteBasicTask(ctx context.Context, db DBTX, id int64) ([]SingleTask, error) {
	rows, err := db.QueryContext(ctx, deleteBasicTask, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SingleTask
	for rows.Next() {
		var i SingleTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBasicTask = `-- name: GetBasicTask :one
SELECT id, created_at, text, description, user_id, start, notification_params
FROM single_tasks
WHERE id = ?1
`

func (q *Queries) GetBasicTask(ctx context.Context, db DBTX, id int64) (SingleTask, error) {
	row := db.QueryRowContext(ctx, getBasicTask, id)
	var i SingleTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.NotificationParams,
	)
	return i, err
}

const listBasicTasks = `-- name: ListBasicTasks :many
SELECT bt.id, bt.created_at, bt.text, bt.description, bt.user_id, bt.start, bt.notification_params
FROM single_tasks as bt
LEFT JOIN smth2tags as s2t
  ON bt.id = s2t.smth_id
LEFT JOIN tags as t
  ON s2t.tag_id = t.id
WHERE bt.user_id = ?1
  AND (
    ?2 IS NULL 
    OR t.id IN (SELECT value FROM json_each(@tag_ids))
  )
ORDER BY bt.id DESC
LIMIT ?4 OFFSET ?3
`

type ListBasicTasksParams struct {
	UserID int64       `db:"user_id"`
	TagIds interface{} `db:"tag_ids"`
	Off    int64       `db:"off"`
	Lim    int64       `db:"lim"`
}

type ListBasicTasksRow struct {
	SingleTask SingleTask `db:"single_task"`
}

func (q *Queries) ListBasicTasks(ctx context.Context, db DBTX, arg ListBasicTasksParams) ([]ListBasicTasksRow, error) {
	rows, err := db.QueryContext(ctx, listBasicTasks,
		arg.UserID,
		arg.TagIds,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBasicTasksRow
	for rows.Next() {
		var i ListBasicTasksRow
		if err := rows.Scan(
			&i.SingleTask.ID,
			&i.SingleTask.CreatedAt,
			&i.SingleTask.Text,
			&i.SingleTask.Description,
			&i.SingleTask.UserID,
			&i.SingleTask.Start,
			&i.SingleTask.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBasicTask = `-- name: UpdateBasicTask :exec
UPDATE single_tasks
SET start       = ?1,
    text        = ?2,
    description = ?3,
    notification_params = ?4
WHERE id = ?5
  AND user_id = ?6
`

type UpdateBasicTaskParams struct {
	Start              time.Time      `db:"start"`
	Text               string         `db:"text"`
	Description        sql.NullString `db:"description"`
	NotificationParams []byte         `db:"notification_params"`
	ID                 int64          `db:"id"`
	UserID             int64          `db:"user_id"`
}

func (q *Queries) UpdateBasicTask(ctx context.Context, db DBTX, arg UpdateBasicTaskParams) error {
	_, err := db.ExecContext(ctx, updateBasicTask,
		arg.Start,
		arg.Text,
		arg.Description,
		arg.NotificationParams,
		arg.ID,
		arg.UserID,
	)
	return err
}
