// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: periodic_tasks.sql

package goqueries

import (
	"context"
	"database/sql"
	"time"
)

const addPeriodicTask = `-- name: AddPeriodicTask :one
INSERT INTO periodic_tasks (user_id,
                             text,
                             start,
                             smallest_period,
                             biggest_period,
                             description,
                             notification_params
)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7)
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

type AddPeriodicTaskParams struct {
	UserID             int64          `db:"user_id"`
	Text               string         `db:"text"`
	Start              time.Time      `db:"start"`
	SmallestPeriod     int64          `db:"smallest_period"`
	BiggestPeriod      int64          `db:"biggest_period"`
	Description        sql.NullString `db:"description"`
	NotificationParams []byte         `db:"notification_params"`
}

func (q *Queries) AddPeriodicTask(ctx context.Context, db DBTX, arg AddPeriodicTaskParams) (PeriodicTask, error) {
	row := db.QueryRowContext(ctx, addPeriodicTask,
		arg.UserID,
		arg.Text,
		arg.Start,
		arg.SmallestPeriod,
		arg.BiggestPeriod,
		arg.Description,
		arg.NotificationParams,
	)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}

const countListPeriodicTasks = `-- name: CountListPeriodicTasks :one
SELECT COUNT(*)
FROM periodic_tasks as pt
LEFT JOIN smth2tags as s2t
  ON pt.id = s2t.smth_id
LEFT JOIN tags as t
  ON s2t.tag_id = t.id
WHERE pt.user_id = ?1
  AND (
    ?2 IS NULL 
    OR t.id IN (SELECT value FROM json_each(@tag_ids))
  )
`

type CountListPeriodicTasksParams struct {
	UserID int64       `db:"user_id"`
	TagIds interface{} `db:"tag_ids"`
}

func (q *Queries) CountListPeriodicTasks(ctx context.Context, db DBTX, arg CountListPeriodicTasksParams) (int64, error) {
	row := db.QueryRowContext(ctx, countListPeriodicTasks, arg.UserID, arg.TagIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePeriodicTask = `-- name: DeletePeriodicTask :many
DELETE
FROM periodic_tasks
WHERE id = ?1
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

func (q *Queries) DeletePeriodicTask(ctx context.Context, db DBTX, id int64) ([]PeriodicTask, error) {
	rows, err := db.QueryContext(ctx, deletePeriodicTask, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.SmallestPeriod,
			&i.BiggestPeriod,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodicTask = `-- name: GetPeriodicTask :one
SELECT id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
FROM periodic_tasks
WHERE id = ?1
`

func (q *Queries) GetPeriodicTask(ctx context.Context, db DBTX, id int64) (PeriodicTask, error) {
	row := db.QueryRowContext(ctx, getPeriodicTask, id)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}

const listPeriodicTasks = `-- name: ListPeriodicTasks :many
SELECT pt.id, pt.created_at, pt.text, pt.description, pt.user_id, pt.start, pt.smallest_period, pt.biggest_period, pt.notification_params
FROM periodic_tasks as pt
LEFT JOIN smth2tags as s2t
  ON pt.id = s2t.smth_id
LEFT JOIN tags as t
  ON s2t.tag_id = t.id
WHERE pt.user_id = ?1
  AND (
    ?2 IS NULL 
    OR t.id IN (SELECT value FROM json_each(@tag_ids))
  )
ORDER BY pt.id DESC
LIMIT ?4 OFFSET ?3
`

type ListPeriodicTasksParams struct {
	UserID int64       `db:"user_id"`
	TagIds interface{} `db:"tag_ids"`
	Off    int64       `db:"Off"`
	Lim    int64       `db:"lim"`
}

type ListPeriodicTasksRow struct {
	PeriodicTask PeriodicTask `db:"periodic_task"`
}

func (q *Queries) ListPeriodicTasks(ctx context.Context, db DBTX, arg ListPeriodicTasksParams) ([]ListPeriodicTasksRow, error) {
	rows, err := db.QueryContext(ctx, listPeriodicTasks,
		arg.UserID,
		arg.TagIds,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeriodicTasksRow
	for rows.Next() {
		var i ListPeriodicTasksRow
		if err := rows.Scan(
			&i.PeriodicTask.ID,
			&i.PeriodicTask.CreatedAt,
			&i.PeriodicTask.Text,
			&i.PeriodicTask.Description,
			&i.PeriodicTask.UserID,
			&i.PeriodicTask.Start,
			&i.PeriodicTask.SmallestPeriod,
			&i.PeriodicTask.BiggestPeriod,
			&i.PeriodicTask.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeriodicTask = `-- name: UpdatePeriodicTask :one
UPDATE periodic_tasks
SET start               = ?1,
    text                = ?2,
    description         = ?3,
    notification_params = ?4,
    smallest_period     = ?5,
    biggest_period      = ?6
WHERE id = ?7
  AND user_id = ?8
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

type UpdatePeriodicTaskParams struct {
	Start              time.Time      `db:"start"`
	Text               string         `db:"text"`
	Description        sql.NullString `db:"description"`
	NotificationParams []byte         `db:"notification_params"`
	SmallestPeriod     int64          `db:"smallest_period"`
	BiggestPeriod      int64          `db:"biggest_period"`
	ID                 int64          `db:"id"`
	UserID             int64          `db:"user_id"`
}

func (q *Queries) UpdatePeriodicTask(ctx context.Context, db DBTX, arg UpdatePeriodicTaskParams) (PeriodicTask, error) {
	row := db.QueryRowContext(ctx, updatePeriodicTask,
		arg.Start,
		arg.Text,
		arg.Description,
		arg.NotificationParams,
		arg.SmallestPeriod,
		arg.BiggestPeriod,
		arg.ID,
		arg.UserID,
	)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}
