linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 2048
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/Dyleme/Notifier)
      - blank
      - dot

linters:
  enable-all: true
  disable:
    - deadcode # deprecated since 1.49
    - ifshort  # deprecated since 1.48
    - structcheck # deprecated since 1.49
    - varcheck  # deprecated since 1.49
    - nosnakecase # deprecated since 1.48
    - scopelint # deprecated since 1.39
    - exhaustivestruct # deprecated since 1.46
    - interfacer # deprecate since 1.38
    - maligned # deprecated since 1.38
    - golint # deprecated since 1.41
    - varnamelen # short variable names is normal for go
    - goerr113 # not possible to use errors.As()
    - depguard # not necessary for small project
    - gochecknoglobals # global variables are widely used in go code
    - wsl # to many empty lines
    - lll # long lines is not always bad
    - ireturn
run:
  issues-exit-code: 1