linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 512
  nolintlint:
    require-explanation: true
    require-specific: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/Dyleme/Notifier)
      - blank
      - dot

issues:
  exclude-rules:
    # disable funlen for all _test.go files
    - path: _test.go
      linters:
        - funlen
        - exhaustruct
  exclude-dirs:
    - cmd/playground

linters:
  enable-all: true
  disable:
    - varnamelen # short variable names is normal for go
    - depguard # not necessary for small project
    - gochecknoglobals # global variables are widely used in go code
    - wsl # to many empty lines
    - lll # long lines is not always bad
    - testpackage # I want to test logic in not exported functions
    - dupl # some code is boilerplate
    - gomnd
    - execinquery
    - ireturn
    - err113
run:
  issues-exit-code: 1
  timeout: 2m
