version: '3.3'
services:
  postgresql:
    image: postgres:16.6-alpine3.21 
    restart: always
    container_name: postgers
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    command: >
      postgres
      -c shared_buffers=64MB
      -c effective_cache_size=128MB
      -c work_mem=4MB
      -c maintenance_work_mem=32MB
      -c max_connections=20
      -c random_page_cost=1.1
      -c checkpoint_completion_target=0.9
      -c autovacuum=on
      -c autovacuum_max_workers=1
      -c logging_collector=off
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
     - "5432:5432"

  migrations:
    image: dyleme/goose:latest
    container_name: migrations
    env_file: .env
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=user=${POSTGRES_USER} database=${POSTGRES_DB} sslmode=${DB_SSL_MODE} password=${POSTGRES_PASSWORD} host=${DB_HOST}
    volumes:
      - ./migrations:/data
    command: up
    depends_on:
      - postgresql


  service:
    image: dyleme/schedudler
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: schedudler
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgresql
      - migrations
