version: '3.3'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password