version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "443:8080"
    volumes:
      - ~/Projects/Notifier/api:/usr/share/nginx/html/doc
    environment:
      API_URL: ./doc/openapi.yaml