version: '3.3'
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgers
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

#  service:
#    image: dyleme/notifier
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    container_name: apod
#    ports:
#      - APP_PORT:${APP_PORT}
#    depends_on:
#      - postgresql
