// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	Message      string
	UserID       int32
	RequiredTime pgtype.Interval
	Periodic     bool
	Done         bool
	Archived     bool
}

type TimetableTask struct {
	ID          int32
	CreatedAt   pgtype.Timestamp
	Text        string
	Description pgtype.Text
	UserID      int32
	Start       pgtype.Timestamp
	Finish      pgtype.Timestamp
	Done        bool
	TaskID      int32
}

type User struct {
	ID           int32
	Email        string
	Nickname     string
	PasswordHash string
}
