// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package queries

import (
	"encoding/json"
	"time"
)

type Notification struct {
	ID               int32
	UserID           int32
	TaskID           int32
	Message          string
	NotificationTime time.Time
	CreationTime     time.Time
	Destination      json.RawMessage
	Sended           bool
}

type Task struct {
	ID           int32
	CreatedAt    time.Time
	Message      string
	UserID       int32
	RequiredTime int64
}

type TimetableTask struct {
	ID        int32
	Message   string
	CreatedAt time.Time
	UserID    int32
	Start     time.Time
	Finish    time.Time
	Done      bool
}
