// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: basic_events.sql

package queries

import (
	"context"

	domains "github.com/Dyleme/Notifier/internal/domains"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBasicEvent = `-- name: AddBasicEvent :one
INSERT INTO basic_events (
  user_id,
  text,
  start,
  description,
  notification_params
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, text, description, user_id, start, notification_params
`

type AddBasicEventParams struct {
	UserID             int32                       `db:"user_id"`
	Text               string                      `db:"text"`
	Start              pgtype.Timestamptz          `db:"start"`
	Description        pgtype.Text                 `db:"description"`
	NotificationParams *domains.NotificationParams `db:"notification_params"`
}

func (q *Queries) AddBasicEvent(ctx context.Context, db DBTX, arg AddBasicEventParams) (BasicEvent, error) {
	row := db.QueryRow(ctx, addBasicEvent,
		arg.UserID,
		arg.Text,
		arg.Start,
		arg.Description,
		arg.NotificationParams,
	)
	var i BasicEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.NotificationParams,
	)
	return i, err
}

const countListBasicEvents = `-- name: CountListBasicEvents :one
SELECT COUNT(*)
FROM basic_events
WHERE user_id = $1
`

func (q *Queries) CountListBasicEvents(ctx context.Context, db DBTX, userID int32) (int64, error) {
	row := db.QueryRow(ctx, countListBasicEvents, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBasicEvent = `-- name: DeleteBasicEvent :many
DELETE
FROM basic_events
WHERE id = $1
RETURNING id, created_at, text, description, user_id, start, notification_params
`

func (q *Queries) DeleteBasicEvent(ctx context.Context, db DBTX, id int32) ([]BasicEvent, error) {
	rows, err := db.Query(ctx, deleteBasicEvent, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BasicEvent
	for rows.Next() {
		var i BasicEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBasicEvent = `-- name: GetBasicEvent :one
SELECT id, created_at, text, description, user_id, start, notification_params
FROM basic_events
WHERE id = $1
`

func (q *Queries) GetBasicEvent(ctx context.Context, db DBTX, id int32) (BasicEvent, error) {
	row := db.QueryRow(ctx, getBasicEvent, id)
	var i BasicEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.NotificationParams,
	)
	return i, err
}

const listBasicEvents = `-- name: ListBasicEvents :many
SELECT id, created_at, text, description, user_id, start, notification_params
FROM basic_events
WHERE user_id = $1
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type ListBasicEventsParams struct {
	UserID int32 `db:"user_id"`
	Off    int32 `db:"off"`
	Lim    int32 `db:"lim"`
}

func (q *Queries) ListBasicEvents(ctx context.Context, db DBTX, arg ListBasicEventsParams) ([]BasicEvent, error) {
	rows, err := db.Query(ctx, listBasicEvents, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BasicEvent
	for rows.Next() {
		var i BasicEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBasicEvent = `-- name: UpdateBasicEvent :one
UPDATE basic_events
SET start       = $1,
    text        = $2,
    description = $3,
    notification_params = $4
WHERE id = $5
  AND user_id = $6
RETURNING id, created_at, text, description, user_id, start, notification_params
`

type UpdateBasicEventParams struct {
	Start              pgtype.Timestamptz          `db:"start"`
	Text               string                      `db:"text"`
	Description        pgtype.Text                 `db:"description"`
	NotificationParams *domains.NotificationParams `db:"notification_params"`
	ID                 int32                       `db:"id"`
	UserID             int32                       `db:"user_id"`
}

func (q *Queries) UpdateBasicEvent(ctx context.Context, db DBTX, arg UpdateBasicEventParams) (BasicEvent, error) {
	row := db.QueryRow(ctx, updateBasicEvent,
		arg.Start,
		arg.Text,
		arg.Description,
		arg.NotificationParams,
		arg.ID,
		arg.UserID,
	)
	var i BasicEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.NotificationParams,
	)
	return i, err
}
