// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: periodic_tasks.sql

package queries

import (
	"context"

	domains "github.com/Dyleme/Notifier/internal/domains"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPeriodicTask = `-- name: AddPeriodicTask :one
INSERT INTO periodic_tasks (user_id,
                             text,
                             start,
                             smallest_period,
                             biggest_period,
                             description,
                             notification_params
)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7)
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

type AddPeriodicTaskParams struct {
	UserID             int32                       `db:"user_id"`
	Text               string                      `db:"text"`
	Start              pgtype.Timestamptz          `db:"start"`
	SmallestPeriod     int32                       `db:"smallest_period"`
	BiggestPeriod      int32                       `db:"biggest_period"`
	Description        pgtype.Text                 `db:"description"`
	NotificationParams *domains.NotificationParams `db:"notification_params"`
}

func (q *Queries) AddPeriodicTask(ctx context.Context, db DBTX, arg AddPeriodicTaskParams) (PeriodicTask, error) {
	row := db.QueryRow(ctx, addPeriodicTask,
		arg.UserID,
		arg.Text,
		arg.Start,
		arg.SmallestPeriod,
		arg.BiggestPeriod,
		arg.Description,
		arg.NotificationParams,
	)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}

const countListPeriodicTasks = `-- name: CountListPeriodicTasks :one
SELECT COUNT(*)
FROM periodic_tasks
WHERE user_id = $1
`

func (q *Queries) CountListPeriodicTasks(ctx context.Context, db DBTX, userID int32) (int64, error) {
	row := db.QueryRow(ctx, countListPeriodicTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePeriodicTask = `-- name: DeletePeriodicTask :many
DELETE
FROM periodic_tasks
WHERE id = $1
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

func (q *Queries) DeletePeriodicTask(ctx context.Context, db DBTX, id int32) ([]PeriodicTask, error) {
	rows, err := db.Query(ctx, deletePeriodicTask, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.SmallestPeriod,
			&i.BiggestPeriod,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodicTask = `-- name: GetPeriodicTask :one
SELECT id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
FROM periodic_tasks
WHERE id = $1
`

func (q *Queries) GetPeriodicTask(ctx context.Context, db DBTX, id int32) (PeriodicTask, error) {
	row := db.QueryRow(ctx, getPeriodicTask, id)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}

const listPeriodicTasks = `-- name: ListPeriodicTasks :many
SELECT id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
FROM periodic_tasks
WHERE user_id = $1
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type ListPeriodicTasksParams struct {
	UserID int32 `db:"user_id"`
	Off    int32 `db:"off"`
	Lim    int32 `db:"lim"`
}

func (q *Queries) ListPeriodicTasks(ctx context.Context, db DBTX, arg ListPeriodicTasksParams) ([]PeriodicTask, error) {
	rows, err := db.Query(ctx, listPeriodicTasks, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Text,
			&i.Description,
			&i.UserID,
			&i.Start,
			&i.SmallestPeriod,
			&i.BiggestPeriod,
			&i.NotificationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeriodicTask = `-- name: UpdatePeriodicTask :one
UPDATE periodic_tasks
SET start               = $1,
    text                = $2,
    description         = $3,
    notification_params = $4,
    smallest_period     = $5,
    biggest_period      = $6
WHERE id = $7
  AND user_id = $8
RETURNING id, created_at, text, description, user_id, start, smallest_period, biggest_period, notification_params
`

type UpdatePeriodicTaskParams struct {
	Start              pgtype.Timestamptz          `db:"start"`
	Text               string                      `db:"text"`
	Description        pgtype.Text                 `db:"description"`
	NotificationParams *domains.NotificationParams `db:"notification_params"`
	SmallestPeriod     int32                       `db:"smallest_period"`
	BiggestPeriod      int32                       `db:"biggest_period"`
	ID                 int32                       `db:"id"`
	UserID             int32                       `db:"user_id"`
}

func (q *Queries) UpdatePeriodicTask(ctx context.Context, db DBTX, arg UpdatePeriodicTaskParams) (PeriodicTask, error) {
	row := db.QueryRow(ctx, updatePeriodicTask,
		arg.Start,
		arg.Text,
		arg.Description,
		arg.NotificationParams,
		arg.SmallestPeriod,
		arg.BiggestPeriod,
		arg.ID,
		arg.UserID,
	)
	var i PeriodicTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Text,
		&i.Description,
		&i.UserID,
		&i.Start,
		&i.SmallestPeriod,
		&i.BiggestPeriod,
		&i.NotificationParams,
	)
	return i, err
}
