// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Dyleme/Notifier/internal/service/service (interfaces: BasicTaskRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/basic_tasks_mocks.go -package=mocks . BasicTaskRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Dyleme/Notifier/internal/domain"
	service "github.com/Dyleme/Notifier/internal/service/service"
	gomock "go.uber.org/mock/gomock"
)

// MockBasicTaskRepository is a mock of BasicTaskRepository interface.
type MockBasicTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasicTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockBasicTaskRepositoryMockRecorder is the mock recorder for MockBasicTaskRepository.
type MockBasicTaskRepositoryMockRecorder struct {
	mock *MockBasicTaskRepository
}

// NewMockBasicTaskRepository creates a new mock instance.
func NewMockBasicTaskRepository(ctrl *gomock.Controller) *MockBasicTaskRepository {
	mock := &MockBasicTaskRepository{ctrl: ctrl}
	mock.recorder = &MockBasicTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicTaskRepository) EXPECT() *MockBasicTaskRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBasicTaskRepository) Add(ctx context.Context, task domain.BasicTask) (domain.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, task)
	ret0, _ := ret[0].(domain.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBasicTaskRepositoryMockRecorder) Add(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBasicTaskRepository)(nil).Add), ctx, task)
}

// Delete mocks base method.
func (m *MockBasicTaskRepository) Delete(ctx context.Context, taskID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBasicTaskRepositoryMockRecorder) Delete(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBasicTaskRepository)(nil).Delete), ctx, taskID)
}

// Get mocks base method.
func (m *MockBasicTaskRepository) Get(ctx context.Context, taskID int) (domain.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, taskID)
	ret0, _ := ret[0].(domain.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBasicTaskRepositoryMockRecorder) Get(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBasicTaskRepository)(nil).Get), ctx, taskID)
}

// List mocks base method.
func (m *MockBasicTaskRepository) List(ctx context.Context, userID int, params service.ListFilterParams) ([]domain.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, params)
	ret0, _ := ret[0].([]domain.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBasicTaskRepositoryMockRecorder) List(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBasicTaskRepository)(nil).List), ctx, userID, params)
}

// Update mocks base method.
func (m *MockBasicTaskRepository) Update(ctx context.Context, task domain.BasicTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBasicTaskRepositoryMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBasicTaskRepository)(nil).Update), ctx, task)
}
