// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Dyleme/Notifier/internal/service/service (interfaces: BasicTaskRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tasks_mocks.go -package=mocks . BasicTaskRepository
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/Dyleme/Notifier/internal/domains"
	service "github.com/Dyleme/Notifier/internal/service/service"
	gomock "go.uber.org/mock/gomock"
)

// MockBasicTaskRepository is a mock of BasicTaskRepository interface.
type MockBasicTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasicTaskRepositoryMockRecorder
}

// MockBasicTaskRepositoryMockRecorder is the mock recorder for MockBasicTaskRepository.
type MockBasicTaskRepositoryMockRecorder struct {
	mock *MockBasicTaskRepository
}

// NewMockBasicTaskRepository creates a new mock instance.
func NewMockBasicTaskRepository(ctrl *gomock.Controller) *MockBasicTaskRepository {
	mock := &MockBasicTaskRepository{ctrl: ctrl}
	mock.recorder = &MockBasicTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicTaskRepository) EXPECT() *MockBasicTaskRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBasicTaskRepository) Add(arg0 context.Context, arg1 domains.BasicTask) (domains.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(domains.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBasicTaskRepositoryMockRecorder) Add(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBasicTaskRepository)(nil).Add), arg0, arg1)
}

// Delete mocks base method.
func (m *MockBasicTaskRepository) Delete(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBasicTaskRepositoryMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBasicTaskRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockBasicTaskRepository) Get(arg0 context.Context, arg1 int) (domains.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(domains.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBasicTaskRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBasicTaskRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockBasicTaskRepository) List(arg0 context.Context, arg1 int, arg2 service.ListParams) ([]domains.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domains.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBasicTaskRepositoryMockRecorder) List(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBasicTaskRepository)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockBasicTaskRepository) Update(arg0 context.Context, arg1 domains.BasicTask) (domains.BasicTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(domains.BasicTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBasicTaskRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBasicTaskRepository)(nil).Update), arg0, arg1)
}
