// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package goqueries

import (
	"time"
)

type KeyValue struct {
	Key   string      `db:"key"`
	Value interface{} `db:"value"`
}

type Sending struct {
	ID              int64     `db:"id"`
	CreatedAt       time.Time `db:"created_at"`
	TaskID          int64     `db:"task_id"`
	NextSending     time.Time `db:"next_sending"`
	OriginalSending time.Time `db:"original_sending"`
	Done            int64     `db:"done"`
}

type Task struct {
	ID                  int64       `db:"id"`
	CreatedAt           time.Time   `db:"created_at"`
	Text                string      `db:"text"`
	Description         string      `db:"description"`
	UserID              int64       `db:"user_id"`
	Type                string      `db:"type"`
	Start               string      `db:"start"`
	EventCreationParams interface{} `db:"event_creation_params"`
}

type TgImage struct {
	Filename string `db:"filename"`
	TgFileID string `db:"tg_file_id"`
}

type User struct {
	ID                       int64 `db:"id"`
	TgID                     int64 `db:"tg_id"`
	TimezoneOffset           int64 `db:"timezone_offset"`
	TimezoneDst              int64 `db:"timezone_dst"`
	NotificationRetryPeriodS int64 `db:"notification_retry_period_s"`
}
