package: timetableapi
generate:
  chi-server: true
  models: true
output: ./internal/timetable-service/handler/timetableapi/timetableapi.gen.go
output-options:
  include-tags:
    - Tasks
    - Events
    - Event
    - NotificationParams