package: api
generate:
  chi-server: true
  models: true
output: ./internal/service/handler/api/timetableapi.gen.go
output-options:
  include-tags:
    - Events
    - Basic tasks
    - Periodic tasks
    - Notification params
    - Tags
