package: api
generate:
  chi-server: true
  models: true
output: ./internal/service/handler/api/timetableapi.gen.go
output-options:
  include-tags:
    - Tasks
    - Events
    - Event
    - NotificationParams